let id=location.pathname.split('/').filter(Boolean).pop(),data,place='',date='',time='',n=0;const $=id=>document.getElementById(id);
async function load(){let r=await fetch('/api/invitations/'+id);if(!r.ok){$('message').textContent='Это приглашение больше недоступно.';return}data=await r.json();$('title').textContent=data.herName+', это для тебя…';$('message').textContent=data.message;fill('places',data.places,'p');fill('dates',data.dates,'d');fill('times',data.times,'t')}
function fill(id,a,type){$(id).innerHTML=a.map((x,i)=>{let q=x.split(' — ');return '<div class="option" onclick="pick(this,\''+type+'\','+i+')"><b>'+esc(q[0])+'</b>'+(q[1]?'<span>'+esc(q.slice(1).join(' — '))+'</span>':'')+'</div>'}).join('')}
function pick(el,t,i){el.parentElement.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');if(t==='p')place=data.places[i];if(t==='d')date=data.dates[i];if(t==='t')time=data.times[i]}
function show(n){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$('s'+n).classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}
function yes(){show(2);burst(15)}function no(){n++;$('yes').style.transform='scale('+Math.min(1.65,1+n*.12)+')';$('no').style.transform='scale('+Math.max(.7,1-n*.06)+')';$('no').textContent=n<3?'Мне нужно подумать 🙈':n<6?'Ты уверена? 🥺':'Ну пожалуйста ❤️';burst(3)}
function next(s){if(s===3&&!place)return alert('Выбери место ❤️');if(s===4&&!date)return alert('Выбери день ❤️');show(s)}
async function finish(){if(!time)return alert('Выбери время ❤️');$('rp').textContent=place;$('rd').textContent=date;$('rt').textContent=time;await fetch('/api/invitations/'+id+'/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answer:'Да ❤️',place,date,time})});show(5);burst(25)}
function burst(k){for(let i=0;i<k;i++)setTimeout(()=>{let e=document.createElement('div');e.className='f';e.textContent=['♡','♥','💕','✨','🌷'][Math.floor(Math.random()*5)];e.style.left=Math.random()*100+'vw';$('hearts').appendChild(e);setTimeout(()=>e.remove(),4500)},i*90)}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}load()
